name: PR Merge Time Difference

on:
  pull_request:
    types: [closed]

jobs:
  time-difference:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history so we can access all commits

      - name: Set PR and Base Branch Names
        run: |
          echo "BASE_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          echo "PR_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Get First PR Commit SHA
        id: first_commit
        run: |
          FIRST_COMMIT_SHA=$(git log --reverse --format="%H" $BASE_BRANCH..$PR_BRANCH | head -n 1)
          echo "First commit in PR is $FIRST_COMMIT_SHA"
          echo "sha=$FIRST_COMMIT_SHA" >> $GITHUB_OUTPUT

      - name: Get Merge Commit SHA
        id: merge_commit
        run: |
          MERGE_COMMIT_SHA=${{ github.event.pull_request.merge_commit_sha }}
          echo "Merge commit in PR is $MERGE_COMMIT_SHA"
          echo "sha=$MERGE_COMMIT_SHA" >> $GITHUB_OUTPUT

      - name: Get First Commit Time
        id: first_commit_time
        run: |
          FIRST_COMMIT_TIME=$(git show -s --format=%ct ${{ steps.first_commit.outputs.sha }})
          echo "time=$FIRST_COMMIT_TIME" >> $GITHUB_OUTPUT

      - name: Get Merge Commit Time
        id: merge_commit_time
        run: |
          MERGE_COMMIT_TIME=$(git show -s --format=%ct ${{ steps.merge_commit.outputs.sha }})
          echo "time=$MERGE_COMMIT_TIME" >> $GITHUB_OUTPUT

      - name: Calculate Time Difference
        run: |
          DIFFERENCE=$((${{ steps.merge_commit_time.outputs.time }} - ${{ steps.first_commit_time.outputs.time }}))
          echo "Time difference in seconds: $DIFFERENCE"
