name: PR Merge Time Difference

on:
  pull_request:
    types: [closed]

jobs:
  time-difference:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history so we can access all commits

      - name: Get First PR Commit SHA
        id: first_commit
        run: |
          FIRST_COMMIT_SHA=$(git rev-list --max-parents=0 HEAD)
          echo "First commit in PR is $FIRST_COMMIT_SHA"
          echo "::set-output name=sha::$FIRST_COMMIT_SHA"

      - name: Get Merge Commit SHA
        id: merge_commit
        run: |
          MERGE_COMMIT_SHA=${{ github.event.pull_request.merge_commit_sha }}
          echo "Merge commit in PR is $MERGE_COMMIT_SHA"
          echo "::set-output name=sha::$MERGE_COMMIT_SHA"

      - name: Get First Commit Time
        id: first_commit_time
        run: |
          FIRST_COMMIT_TIME=$(git show -s --format=%ct ${{ steps.first_commit.outputs.sha }})
          echo "::set-output name=time::$FIRST_COMMIT_TIME"

      - name: Get Merge Commit Time
        id: merge_commit_time
        run: |
          MERGE_COMMIT_TIME=$(git show -s --format=%ct ${{ steps.merge_commit.outputs.sha }})
          echo "::set-output name=time::$MERGE_COMMIT_TIME"

      - name: Calculate Time Difference
        run: |
          DIFFERENCE=$((${{ steps.merge_commit_time.outputs.time }} - ${{ steps.first_commit_time.outputs.time }}))
          echo "Time difference in seconds: $DIFFERENCE"
